bind = $mainMod, G, togglespecialworkspace, steam
bind = $mainMod SHIFT, G, movetoworkspace, special:steam


windowrule{
  name = steamWorkspace
    match:class = ^(steam)$
    workspace = special:steam
}

windowrule {
  name = steamWindows
    match:class =^(steam)$
    match:initial_title = negative:^(Friends List)$
    match:title = negative:^(Steam)$ 
    float=yes
}

windowrule{
  name = friendsList
    match:initial_title = ^(Friends List)$
    size = 100 200
}


