
$exec = exec, uwsm app --

$bar = quickshell
$menu = hyprlauncher
$shell = fish
$terminal = ghostty
$editor = nvim
$fileManager = thunar
$browser = zen-browser


$mainMod = SUPER # Sets "Windows" key as main modifier

env = HYPRCURSOR_SIZE,24
